/** Opções e rótulos de tipo de conteúdo (ativação e filtros). */
export const CONTENT_TYPE_OPTIONS = [
  { value: 'fitness', label: 'Fitness' },
  { value: 'moda', label: 'Moda' },
  { value: 'beleza', label: 'Beleza' },
  { value: 'lifestyle', label: 'Lifestyle' },
  { value: 'viagens', label: 'Viagens' },
  { value: 'gastronomia', label: 'Gastronomia' },
  { value: 'tecnologia', label: 'Tecnologia' },
  { value: 'games', label: 'Games' },
  { value: 'musica', label: 'Música' },
  { value: 'entretenimento', label: 'Entretenimento' },
  { value: 'conteudo_adulto', label: 'Conteúdo adulto' },
  { value: 'mae_pai', label: 'Maternidade / Paternidade' },
  { value: 'pet', label: 'Pets' },
  { value: 'negocios', label: 'Negócios / Empreendedorismo' },
  { value: 'educacao', label: 'Educação' },
  { value: 'saude', label: 'Saúde' },
  { value: 'esportes', label: 'Esportes' },
  { value: 'humor', label: 'Humor' },
  { value: 'politica', label: 'Política / Atualidades' },
  { value: 'automotivo', label: 'Automotivo' },
  { value: 'decoracao', label: 'Decoração / Casa' },
  { value: 'literatura', label: 'Literatura' },
  { value: 'arte_cultura', label: 'Arte e cultura' },
  { value: 'cinema', label: 'Cinema / Filmes' },
  { value: 'danca', label: 'Dança' },
  { value: 'diy', label: 'DIY / Faça você mesmo' },
  { value: 'eventos', label: 'Eventos' },
  { value: 'financas', label: 'Finanças pessoais' },
  { value: 'imoveis', label: 'Imóveis' },
  { value: 'jornalismo', label: 'Jornalismo' },
  { value: 'moda_sustentavel', label: 'Moda sustentável' },
  { value: 'musculacao', label: 'Musculação' },
  { value: 'nutricao', label: 'Nutrição' },
  { value: 'religiao', label: 'Religião / Espiritualidade' },
  { value: 'sustentabilidade', label: 'Sustentabilidade' },
  { value: 'turismo', label: 'Turismo' },
  { value: 'vegano', label: 'Vegan / Vegetariano' },
  { value: 'yoga', label: 'Yoga / Meditação' },
  { value: 'comedia', label: 'Comédia' },
  { value: 'reviews', label: 'Crítica / Reviews' },
  { value: 'creator', label: 'Influencer digital / Creator' },
  { value: 'luxo', label: 'Luxo' },
  { value: 'minimalismo', label: 'Minimalismo' },
  { value: 'plus_size', label: 'Plus size' },
  { value: 'maquiagem', label: 'Maquiagem' },
  { value: 'cabelo', label: 'Cabelo' },
  { value: 'skincare', label: 'Skincare' },
  { value: 'unhas', label: 'Unhas' },
  { value: 'moda_masculina', label: 'Moda masculina' },
  { value: 'moda_feminina', label: 'Moda feminina' },
  { value: 'streetwear', label: 'Streetwear' },
  { value: 'casamento', label: 'Casamento' },
  { value: 'festas', label: 'Festas' },
  { value: 'culinaria', label: 'Culinária' },
  { value: 'cafes', label: 'Cafés' },
  { value: 'vinhos', label: 'Vinhos / Bebidas' },
  { value: 'corrida', label: 'Corrida' },
  { value: 'ciclismo', label: 'Ciclismo' },
  { value: 'natacao', label: 'Natação' },
  { value: 'crossfit', label: 'CrossFit' },
  { value: 'futebol', label: 'Futebol' },
  { value: 'outro', label: 'Outro' },
]

export const CONTENT_TYPE_LABELS: Record<string, string> = Object.fromEntries(
  CONTENT_TYPE_OPTIONS.map((o) => [o.value, o.label])
)
